# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_GTRACE) += gtrace.o
gtrace-y := gtrace-core.o

obj-$(CONFIG_RVTRACE) += rvtrace-platform.o
obj-$(CONFIG_RVTRACE_ENCODER) += rvtrace-encoder.o
obj-$(CONFIG_RVTRACE_RAMSINK) += rvtrace-ramsink.o
