# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_GTRACE) += gtrace.o
gtrace-y := gtrace-core.o
gtrace-$(CONFIG_OF) += gtrace-of.o

obj-$(CONFIG_RVTRACE) += rvtrace-platform.o
obj-$(CONFIG_RVTRACE_ENCODER) += rvtrace-encoder.o
